platform:
  - x64
services:
  - mysql

skip_commits:
  files:
    - "*.yml"
    - "*.rst"
    - "LICENSE"

build: off

install:
  - ps: $env:MYSQL_PWD="root"
  - ps: $cmd = '"C:\Program Files\MySQL\MySQL Server 5.7\bin\mysql" -e "create database start;" --user=root --default-character-set=utf8 start < environment/db/start.sql'
  - ps: $cmd = '"C:\Program Files\MySQL\MySQL Server 5.7\bin\mysql" -e "GRANT ALL PRIVILEGES ON *.* TO root@'%' IDENTIFIED BY '.'; FLUSH PRIVILEGES;"'
  - ps: $cmd = '"C:\Program Files\MySQL\MySQL Server 5.7\bin\mysql" -e "use mysql; update user set authentication_string=PASSWORD('root') where User='root'; update user set plugin='mysql_native_password';FLUSH PRIVILEGES;"'
  - ps: iex "& $cmd"

test_script:
  # Start Proxy
  #- ps: Start-Process -FilePath o_o -NoNewWindow
  - systeminfo
  - mvn test -B -f .\pom.xml

