language: java
sudo: true # faster builds

jdk:
  - openjdk8

services:
  - mysql
  - redis

addons:
  apt:
    sources:
      - mysql-5.7-trusty
    packages:
      - mysql-server

before_install:
  - sudo mysql -e 'CREATE DATABASE start;'
  - mysql -u root --default-character-set=utf8 start < environment/db/start.sql
  - mysql_upgrade -u root
  - sudo mysql -e "GRANT ALL PRIVILEGES ON *.* TO root@'%' IDENTIFIED BY '.'; FLUSH PRIVILEGES;"
  - sudo mysql -e "use mysql; update user set authentication_string=PASSWORD('root') where User='root'; update user set plugin='mysql_native_password';FLUSH PRIVILEGES;"

script:
  - mvn clean package -B -f pom.xml
