#############################################
#               应用配置文件                  #
#    https://www.renfei.net 极速版           #
#    author: RenFei(i@renfei.net)           #
#    Copyright © 2021 RENFEI.NET            #
#############################################
# Server ####################################
server:
  port: 8081
  servlet:
    session:
      cookie:
        max-age: P7D
# Spring ####################################
spring:
  profiles:
    ## 运行环境配置
    active: @activatedProperties@
  servlet:
    multipart:
      max-file-size: 32MB
      max-request-size: 64MB
  messages:
    basename: i18n/messages
  datasource:
    druid:
      initial-size: 10
      max-active: 100
      min-idle: 10
      max-wait: 60000
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
      validation-query: SELECT 1 FROM DUAL
      validation-query-timeout: 600
      test-on-borrow: false
      test-on-return: false
      test-while-idle: true
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      filter:
        wall:
          enabled: true
        stat:
          ## 慢SQL打印
          log-slow-sql: true
          slow-sql-millis: 5
      filters: stat,wall,slf4j,config
      login:
        username: renfei
        password: renfei
      allow: 10.10.0.218
      deny: 192.168.1.1
  ## freemarker 配置
  freemarker:
    template-loader-path: classpath:/templates
    charset: UTF-8
    check-template-location: true
    content-type: text/html
    expose-request-attributes: true
    expose-session-attributes: true
    request-context-attribute: request
    suffix: .ftl
  cache:
    type: redis
  redis:
    lettuce:
      pool:
        max-active: 10 # 连接池最大连接数
        max-idle: 10 # 连接池最大空闲连接数
        min-idle: 0 # 连接池最小空闲连接数
        max-wait: -1ms # 连接池最大阻塞等待时间，负值表示没有限制
    timeout: 1200
  ## Session 存储位置配置
  session:
    store-type: redis
    timeout: P7D
  quartz:
    job-store-type: jdbc
    properties:
      org:
        quartz:
          scheduler:
            #调度任务实例名称，如果是集群则每个实例必须是相同的名字
            instanceName: SmallGrainScheduler
            #实例ID，对于集群中工作的所有调度器必须是唯一的，如果值是AUTO则会自动生成，如果希望值来自系统属性则设置为SYS_PROP
            instanceId: AUTO
          jobStore:
            #job、traggers、calendars持久化实现类，默认：org.quartz.simpl.RAMJobStore
            class: org.quartz.impl.jdbcjobstore.JobStoreTX
            #调度程序下次触发时间的毫秒数，默认是60000（60 seconds）
            misfireThreshold: 60000
            #驱动程序代理类
            driverDelegateClass: org.quartz.impl.jdbcjobstore.StdJDBCDelegate
            #表名前缀，默认：QRTZ_
            tablePrefix: T_QUATRZ_
            #默认：false，设置JDBCJobStore的JobDataMaps中存储的是字符串类型的key-value,否则为 true
            useProperties: false
            #设置为true以启用集群功能，如果Quartz的多个实例使用同一组数据库表，则必须将此属性设置为true,否则将遇到严重的破话，默认：false
            isClustered: true
            #设置此实例与集群的其它实例"checks-in"的频率（毫秒），影响实例的检测失败速率，默认：15000
            clusterCheckinInterval: 10000
          #配置线程池
          threadPool:
            #要使用的线程池实心名称，与Quartz自带的线程池应该可以满足几乎每个用户的需求，它的行为非常简单，而且已经过很好的测试，它提供了一个固定大小的线程池，这些线程在调度程序的生存期内"生存"
            class: org.quartz.simpl.SimpleThreadPool
            #线程数
            threadCount: 10
            #线程优先级，可以是Thread.MIN_PRIORITY（1）和Thread.MAX_PRIORITY（10）之间的数据，默认是：Thread.NORM_PRIORITY (5)
            threadPriority: 5
            #可以设置为true以将线程池中的线程创建为守护程序线程。默认：false
            makeThreadsDaemons: false
            #线程池中线程名的前缀,默认：MyScheduler_Worker
            threadNamePrefix: MyScheduler_Worker
            #默认true
            threadsInheritGroupOfInitializingThread: true
            #默认true
            threadsInheritContextClassLoaderOfInitializingThread: true

# feign #####################################
feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: basic
# MyBatis ###################################
mybatis:
  mapper-locations: classpath:mapper/mysql/*.xml
  configuration:
    ## 开启驼峰命名
    map-underscore-to-camel-case: true
    ## 打印SQL
    #log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql