#############################################
#               应用配置文件                  #
#    https://www.renfei.net 极速版           #
#    author: RenFei(i@renfei.net)           #
#    Copyright © 2021 RENFEI.NET            #
#############################################
# Server ####################################
server:
  port: 8081
  servlet:
    session:
      cookie:
        max-age: P7D
# Spring ####################################
spring:
  profiles:
    ## 运行环境配置
    active: @activatedProperties@
  servlet:
    multipart:
      max-file-size: 32MB
      max-request-size: 64MB
  messages:
    basename: i18n/messages
  datasource:
    druid:
      initial-size: 10
      max-active: 100
      min-idle: 10
      max-wait: 60000
      pool-prepared-statements: true
      max-pool-prepared-statement-per-connection-size: 20
      validation-query: SELECT 1 FROM DUAL
      validation-query-timeout: 600
      test-on-borrow: false
      test-on-return: false
      test-while-idle: true
      time-between-eviction-runs-millis: 60000
      min-evictable-idle-time-millis: 300000
      filter:
        wall:
          enabled: true
        stat:
          ## 慢SQL打印
          log-slow-sql: true
          slow-sql-millis: 5
      filters: stat,wall,slf4j,config
      login:
        username: renfei
        password: renfei
      allow: 10.10.0.218
      deny: 192.168.1.1
  ## freemarker 配置
  freemarker:
    template-loader-path: classpath:/templates
    charset: UTF-8
    check-template-location: true
    content-type: text/html
    expose-request-attributes: true
    expose-session-attributes: true
    request-context-attribute: request
    suffix: .ftl
  cache:
    type: redis
  redis:
    lettuce:
      pool:
        max-active: 10 # 连接池最大连接数
        max-idle: 10 # 连接池最大空闲连接数
        min-idle: 0 # 连接池最小空闲连接数
        max-wait: -1ms # 连接池最大阻塞等待时间，负值表示没有限制
    timeout: 1200
  ## Session 存储位置配置
  session:
    store-type: redis
    timeout: P7D
# feign #####################################
feign:
  client:
    config:
      default:
        connectTimeout: 5000
        readTimeout: 5000
        loggerLevel: basic
# MyBatis ###################################
mybatis:
  mapper-locations: classpath:mapper/mysql/*.xml
  configuration:
    ## 开启驼峰命名
    map-underscore-to-camel-case: true
    ## 打印SQL
    #log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql